### ISSUE TITLE
Search for private keys

### ISSUE THREAD

**Issue by Brovada** [TheZ3ro/bitcoin-privatekey-db#1]
Do you have any idea how I can think with the keys inside the page?

I would like to add a search box, but I'm having a headache to implement a search engine. Can you help me?

**Comment by john2211** [comment]
how to find private key of any wallet address

**Comment by maronno** [comment]
plz sir how do i can have all bitcoin plz halp

regards

**Comment by TheZ3ro** [comment]
Citing the Readme:

> A private key it's just a number chosen randomly from a range, if this range (called key-space) is big enough it won't be possible to list all the keys in feasible times.
> 
> Bitcoin private keys range from 1 to 115792089237316195423570985008687907852837564279074904382605163141518161494336
> 
> The key-space it's too big to index all the keys (http://redd.it/1rurll), but you can however generate private keys on demand.
> 
> For this reason I have developed this on-demand database and also a Lottery that will take a random private key from the key-space and tell you if it has some bitcoin available. ;)

So it's a Joke project essentially. 
It's not possible to search for a specific private key and it's not possible to list all the keys at the same time.

If you want free bitcoin visit: https://t.co/HklF0xyiE2
