### ISSUE TITLE
How the fuck do you launch the server?

### ISSUE THREAD

**Issue by natedawg469** [TheZ3ro/bitcoin-privatekey-db#2]
I'm trying to use pythonanywhere to deploy this and I just can't figure it out.

**Comment by sycomix** [comment]
pip install -r requirements.txt 
./run.sh

mind that you have all dependents in place, tested working in debian 8-9.5 and ubuntu 16.04-19.10 beta and OS X

I don't do windows, sorry pal.

**Comment by TheZ3ro** [comment]
Installation is specified in the readme. Also thanks @sycomix. Closing
