### ISSUE TITLE
Do not show balance?

### ISSUE THREAD

**Issue by omegazoe** [TheZ3ro/bitcoin-privatekey-db#3]
Your source code is installed differently from your web page. No balance is displayed.

**Comment by john2211** [comment]
can explain detaiL regerding wHAT

**Comment by TheZ3ro** [comment]
What balance? The webpage doesn't show any balance, I don't understand what you mean

**Comment by ghost** [comment]
how to see the balance?

**Comment by timekswaste** [comment]
> What balance? The webpage doesn't show any balance, I don't understand what you mean

please update blance show like this website similor >>>>> https://keys.lol/bitcoin/1
and lanch website setp by step guide please

**Comment by timekswaste** [comment]
please update qick

**Comment by timekswaste** [comment]
> how to see the balance?

please update blance show like this website similor >>>>> https://keys.lol/bitcoin/1
and lanch website setp by step guide please

**Comment by timekswaste** [comment]
> What balance? The webpage doesn't show any balance, I don't understand what you mean

website run for github.io updade please
contect me 321okokgod2@gmail.com
