### ISSUE TITLE
too slow

### ISSUE THREAD

**Issue by omegazoe** [TheZ3ro/bitcoin-privatekey-db#4]
The program is too slow, producing 127,000 for 13 minutes

**Comment by john2211** [comment]
SO WAT I DO SIR

**Comment by TheZ3ro** [comment]
`¯\_(ツ)_/¯`

**Comment by hitendrapharmacy** [comment]
sir can you make these program to scan only addresses and match with own database addresses......will be faster!!!!.....as no need to check balances?
