### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by PlamenOBM** [TheZ3ro/bitcoin-privatekey-db#6]
File:"bitcoin-privatekey-db/server.py", line 23, in secret_to_address
    if to_sec > MAX_EXPONENT:
        to_sec = MAX_EXPONENT
    return range(from_sec+1,to_sec+1)
 
def secret_to_address(secret_exponent):
    k = Key(secret_exponent=secret_exponent)
    addr = k.address(use_uncompressed=True)
Open an interactive python shell in this frame    ​caddr = k.address(
    wif = k.wif(use_uncompressed=True)
    return secret_exponent, wif, addr, caddr
 
TypeError: 'module' object is not callable

**Comment by timekswaste** [comment]
please update blance show like this website similor >>>>> https://keys.lol/bitcoin/1
and lanch website setp by step guide please

**Comment by timekswaste** [comment]
please update blance show like this website similor >>>>> https://keys.lol/bitcoin/1
and lanch website setp by step guide please
